reply_warning_message:
  default: "This topic is closed - normal users cannot reply. Would you like to use your staff privileges to reply anyway?"
  description:
    en: The message displayed to admins who try and reply to a closed topic.